export const SET_TOP_MESSAGE = 'SET_TOP_MESSAGE'

export const RECEIVE_PROFILE = 'RECEIVE_PROFILE'

export const RECEIVE_CARDS = 'RECEIVE_CARDS'

export const RECEIVE_PREVIEW = 'RECEIVE_PREVIEW'

export const CHANGE_LOCALE = 'CHANGE_LOCALE'

export const CHANGE_CURRENT_USER = 'CHANGE_CURRENT_USER'
